name: Publish to GitHub Packages

on:
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Даёт доступ к GitHub Packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Publish
        run: mvn deploy -DskipTests
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}  # Авторизация в GitHub Packages